### ISSUE TITLE
Private DNS Zone for Acr not connected to Azure DNS resolver

### ISSUE THREAD

**Issue by NeelabhKher** [paolosalvatori/private-aks-cluster#2]
Should the Azure DNS resolver be connected to the Private DNS Zone for Acr ?

**Comment by paolosalvatori** [comment]
@NeelabhKher sorry for the delayed answer. 
- The [ARM template that deploys a single node pool](https://github.com/paolosalvatori/private-aks-cluster/blob/master/templates/one-node-pool/azuredeploy.json) does not deploy any ACR so this issue is not applicable. 
- The [ARM template that deploys two node pools](https://github.com/paolosalvatori/private-aks-cluster/blob/master/templates/two-node-pools/azuredeploy.json) creates a private endpoint ONLY if the ACR SKU is Premium as this is the only SKU that supports private endpoints. In this case, a [PrivateDnsZoneGroup](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/privateendpoints/privatednszonegroups) child resource is created for the private endpoint. This resource is responsible to create an A record in the target private privatelink.azurecr.io Private DNS Zone when the private endpoint gets created and delete the A record when the private endpoint gets deprovisioned. In other words, the template already does what you are asking for ☺️

**Comment by NeelabhKher** [comment]
thank you!!
